/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import interfazadmin.Conector;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emilio
 */
public class adminTrabajadores extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    String num;
    Connection conexion;
    DefaultTableModel m;
    private int puesto;
    private int numeroEmpleado;
    public adminTrabajadores(int puesto, int nE) {
        initComponents();
        this.setLocationRelativeTo(null);
        tabla.getTableHeader().setReorderingAllowed(false) ;
        this.puesto=puesto;
        this.numeroEmpleado=nE;
        mostrarTabla();
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/auto.jpg"));
        return retValue;
    }
    public void mostrarTabla(){
        
        DefaultTableModel m = new DefaultTableModel();
        m.addColumn("NumeroEmpleado");
        m.addColumn("Puesto");
        m.addColumn("Nombre");
        m.addColumn("Apellido");
        m.addColumn("Telefono");
        m.addColumn("Fecha registro");
        tabla.setModel(m);
        
        String sql = "SELECT numeroEmpleado, puesto, nombre, apellido, telefono, fecha FROM trabajadores";
        
        String datos[]=new String[6];
        try{
            Conector.sentencia=Conector.con.createStatement();
            ResultSet r=Conector.sentencia.executeQuery(sql);
            while(r.next()){
                datos[0]=r.getString("numeroEmpleado");
                datos[1]=r.getString("puesto");
                datos[2]=r.getString("nombre");
                datos[3]=r.getString("apellido");
                datos[4]=r.getString("telefono");
                datos[5]=r.getString("fecha");
                m.addRow(datos);
            }
            tabla.setModel(m);
        }catch(SQLException ex){
            Logger.getLogger(adminTrabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalir = new javax.swing.JButton();
        jActualiza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de administración de solicitudes de clientes.");
        setIconImage(getIconImage());

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jActualiza.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jActualiza.setText("Actualizar");
        jActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizaActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jActualiza)
                .addGap(180, 180, 180)
                .addComponent(jEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jActualiza)
                    .addComponent(jEliminar)
                    .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizaActionPerformed
       mostrarTabla();
    }//GEN-LAST:event_jActualizaActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
//Falta validar cuando no se selecciona nada
            int fila=tabla.getSelectedRow();
            String valor=tabla.getValueAt(fila, 1).toString();
            int puesto=Integer.parseInt(valor);
                if(this.puesto>puesto){
                    int opcion=JOptionPane.showOptionDialog(null, 
                                "Desea borrar al empleado numero"+valor+" ?", 
                                "Borrar?", 
                                JOptionPane.YES_NO_OPTION, 
                                JOptionPane.QUESTION_MESSAGE, 
                                null, null, null);
                    if(opcion==0){
                        try {
                            PreparedStatement pps=Conector.con.prepareStatement("DELETE FROM persons WHERE Id='"+valor+"'");
                            pps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Dato eliminado.");
                            mostrarTabla();
                        } catch (SQLException ex) {
                            Logger.getLogger(adminTrabajadores.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else{
                    if(Integer.parseInt(tabla.getValueAt(fila, 0).toString())==this.numeroEmpleado){
                       JOptionPane.showMessageDialog(null, "No te puedes eliminar a ti mismo."); 
                    }else{
                        JOptionPane.showMessageDialog(null, "No tienes los permisos para eliminar a este usuario.");
                    }
                }
    }//GEN-LAST:event_jEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jActualiza;
    private javax.swing.JButton jEliminar;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
